### ISSUE TITLE
Implement search bar functionality

### ISSUE THREAD

**Issue by philchi** [cse110-sp24-group32/cse110-sp24-group32#32]
**Description**

- Add functionality for search bar which searches within a project all the notes whose tags or content contains the query string
- Users should be able to click on the search results to view the note and jump to whatever project the note is in.

**Comment by richmass1** [comment]
Some things to think about:
- Do we want to search by clicking an "enter" button, pressing the enter key, or both? (currently the HTML has no enter button) ([this](https://stackoverflow.com/questions/20484738/submit-form-on-enter-key-with-javascript) provides some tips on using the enter key)
- What should the search results look like?

**Comment by philchi** [comment]
Ideally, I think we would want both to work. If possible, implementing live search would be even more ideal.

**Comment by richmass1** [comment]
My opinion: I like enter key functionality; I don't think a search button is absolutely necessary but if other people really want it, we can add one. I think live search is possible, we would just have to make the search function trigger on any keystroke rather than just the enter key.

**Comment by richmass1** [comment]
For displaying the search results, should we make a figma?

**Comment by philchi** [comment]
I think that's a good idea
